services:
  db:
    image: postgres:latest
    container_name: veterinary_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: veterinary_db
    networks:
      - shared-network
    ports:
      - "5432:5432"


networks:
  shared-network:
    external: true