# name: CD to Production

# on:
#   workflow_run:
#     workflows: ["CI"]
#     types:
#       - completed
#     branches:
#       - main

# jobs:
#   deploy:
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.9.0
#         with:
#           ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}

#       - name: Deploy to Production
#         run: |
#           ssh-keyscan -H ${{ secrets.PROD_SERVER_HOST }} >> ~/.ssh/known_hosts

#           ssh ${{ secrets.PROD_SERVER_USER }}@${{ secrets.PROD_SERVER_HOST }} << 'EOF'
#             cd /home/sgxt/SGXOrchestator

#             echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

#             export TAG=latest

#             docker compose -f docker-compose.yml -f docker-compose.prod.yml pull fastapi-app
#             docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --no-deps fastapi-app

#             docker image prune -f

#             docker logout ghcr.io

#           EOF